modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="wartdecay"
version="${file.jarVersion}"
displayName="Wart Decay"
logoFile="logo.png"
credits=""
authors="Dhyces"
description='''
Makes wart blocks decay in a similar way to leaves
'''

[[dependencies.wartdecay]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wartdecay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wartdecay]]
    modId="statement"
    mandatory=true
    versionRange="[4.2.5,)"
    ordering="NONE"
    side="BOTH"
